version: '3'

services:
  mediaserver:
    build:
      network: host
      context: ./mediaserver
      dockerfile: Dockerfile
    image: mediaserver
    container_name: mediaserver
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGO_USER=jnelson
      - MONGO_PASS=pass
      - ASPNETCORE_URLS=http://0.0.0.0:3000
    volumes:
      - type: bind
        source: /media/disk/HomeMediaCenter/mediaserver/assets
        target: /app/assets

  homemediaplayer:
    build:
      context: ./homemediaplayer
      dockerfile: Dockerfile
    image: homemediaplayer
    container_name: homemediaplayer
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: /media/disk/HomeMediaCenter/homemediaplayer/node_modules
        target: /usr/src/app/node_modules

  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: /media/disk/mongo-data/
        target: /mongo-data/