version: '3'

services:
  mediaserver:
    build:
      context: ./mediaserver
      dockerfile: Dockerfile
    image: mediaserver
    container_name: mediaserver
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: /media/disk/HomeMediaCenter/mediaserver/assets
        target: /usr/src/app/assets
      - type: bind
        source: /media/disk/HomeMediaCenter/mediaserver/node_modules
        target: /usr/src/app/node_modules
