version: '3'

services:
  mediaserver:
    build:
      network: host
      context: ./mediaserver
      dockerfile: Dockerfile
    image: mediaserver
    container_name: mediaserver
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: /media/disk/HomeMediaCenter/mediaserver/assets
        target: /usr/src/app/assets
      - type: bind
        source: /media/disk/HomeMediaCenter/mediaserver/node_modules
        target: /usr/src/app/node_modules

  homemediaplayer:
    build:
      context: ./homemediaplayer
      dockerfile: Dockerfile
    image: homemediaplayer
    container_name: homemediaplayer
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: /media/disk/HomeMediaCenter/homemediaplayer/node_modules
        target: /usr/src/app/node_modules

  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin-user
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - MONGO_USER=jnelson
      - MONGO_PASS=pass
    volumes:
      - mongo-data:/var/lib/mongodb